---
# Restart services that depend on the host environment.
- name: restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: restart unattended-upgrades
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted