# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: caee2c84d5700f65aa7be4b3e365a0ceebff5110
_src_path: gh:42WASD/template-docs-project
project_name: 42wasd-mc
project_slug: 42wasd-mc
org: 42WASD
author: jya0