---
- name: Check for NVIDIA GPU
  ansible.builtin.command: lspci | grep -i nvidia
  register: nvidia_present
  changed_when: false
  failed_when: false

- name: Install NVIDIA driver
  ansible.builtin.apt:
    name: "nvidia-driver-{{ nvidia_cuda_ver }}"
    state: present
  when: nvidia_present.stdout != ""

- name: Install NVIDIA container toolkit
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
  when: nvidia_container_toolkit and nvidia_present.stdout != ""