apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: cockroachdb
    app.kubernetes.io/name: cockroachdb
  name: cockroachdb-rotate-self-signer
  namespace: prd-games-42wasd-admin
