---
- name: Create mount points
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0755"
  loop: "{{ storage_mounts }}"

- name: Mount storage devices
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype | default('ext4') }}"
    opts: "{{ item.opts | default('defaults') }}"
    state: mounted
  loop: "{{ storage_mounts }}"